---
- name: Destroy Azure RG using Ansible
  hosts: localhost
  connection: local
  vars:
    azure_region: westeurope
    resource_group_name: automation-class-ansible-1

  tasks:
  - name: Destroy Azure Deploy
    azure_rm_deployment:
      state: absent
      resource_group_name: "{{resource_group_name}}"
